# Generated by Django 4.2.1 on 2023-09-18 06:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_alter_blog_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('B', 'Editor')], default='A', max_length=1),
        ),
    ]
