# Generated by Django 4.2.1 on 2023-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registered_on', models.DateField()),
                ('account_type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], default='R', max_length=1)),
            ],
        ),
    ]
