# Generated by Django 4.2.1 on 2023-09-18 04:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_blog_person_birth_date_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blog_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
