# Generated by Django 4.2.1 on 2023-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_managers_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stories_filed', models.IntegerField()),
            ],
        ),
    ]
