# Generated by Django 4.2.1 on 2023-09-21 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bookauthor_publisher_remove_book_author_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 6, 56, 50, 335095)),
        ),
    ]
