# Generated by Django 4.2.1 on 2023-09-21 06:58

from django.db import migrations


def update_product_description(apps, schema_editor):
    # Get the Book model
    Product = apps.get_model("myapp", "Product")
    # update the description for all product
    for product in Product.objects.all():
        product.description = f"{product.name}: {product.description}"
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_book_pubdate'),
    ]

    operations = [
        migrations.RunPython(update_product_description),
    ]
