# Generated by Django 4.2.1 on 2023-09-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_quantity_alter_book_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='product_category', on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
